### ISSUE TITLE
HLAPI classes overriding "equals" but not "hashCode"

### ISSUE THREAD

**Issue by balrok** [lip6/pnmlframework#9]
Hello,
putting objects from the HLAPI into a HashMap produces unexpected results as they get added repeatedly.
A solution would be to override hashCode and return the hashCode of the containedItem.

See also here:
http://stackoverflow.com/questions/27581/what-issues-should-be-considered-when-overriding-equals-and-hashcode-in-java

**Comment by yanntm** [comment]
The semantics is fine, 

It's normal to be unable to hash EObject, the basic algorithm would require comparing subtrees.
An EObject is a rooted tree, arbitrarily large.
See also ECoreUtil.equals to compare equality of subtrees/EMF objects.

Either make sure memory identity hash/equals is the right semantics; or index your objects with something else unique to them (e.g. their name, their PNML id...). My usual approach is to build some String reperesentation of the EObject and hash that, or to avoid the hash entirely.

See also this so question : 
http://stackoverflow.com/questions/6252383/using-emf-objects-as-keys
